services:
  server:
    image: "swiftlang/swift:nightly-focal"
    volumes:
      - /Users/prasadrajalingamgari/Documents/Winter_Term/SE:/code
    environment:
      - USER=prasadrajalingamgari
    command: bash -c "apt-get update && apt-get install nodejs && node /code/app.js"

  swift-client:
    image: "swiftlang/swift:nightly-focal"
    volumes:
      - /Users/prasadrajalingamgari/Documents/Winter_Term/SE:/code
    environment:
      - USER=prasadrajalingamgari


  rust-client:
    image: "library/rust:latest"
    volumes:
      - /Users/prasadrajalingamgari/Documents/Winter_Term/SE:/code
    environment:
      - USER=prasadrajalingamgari
      
    

